name: 'air_traffic'
version: '1.0.0'
config-version: 2

profile: 'air_traffic'

model-paths: ["models"]
seed-paths: ["seeds"]
test-paths: ["tests"]
analysis-paths: ["analyses"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

models:
  air_traffic:
    marts:
      +materialized: view
      +schema: marts
    staging:
      +materialized: view
      +schema: staging
