"""Upload the Medallion layers to a Hugging Face dataset repository.

The Hugging Face Hub is used as the free, versioned data lake backing store.
Requires a write token (``HF_TOKEN``) and an existing (or auto-created) repo
named via ``HF_REPO``.

Usage:
    python -m scripts.upload_hf
"""

from __future__ import annotations

import json
from pathlib import Path
from typing import Any

from config.logging import logger
from config.settings import settings


def _plan_uploads() -> list[tuple[Path, str]]:
    """(local_path, repo_path_in_hub) for every Parquet artifact."""
    uploads: list[tuple[Path, str]] = []

    # Silver layer
    silver = settings.silver_dir
    if silver.exists():
        for path in sorted(silver.rglob("*.parquet")):
            uploads.append((path, path.relative_to(silver).as_posix()))

    # Gold layer
    gold = settings.gold_dir
    if gold.exists():
        for path in sorted(gold.rglob("*.parquet")):
            uploads.append((path, path.relative_to(gold).as_posix()))

    # DuckDB warehouse
    if settings.duckdb_path.exists():
        uploads.append((settings.duckdb_path, settings.duckdb_path.name))

    return uploads


def _write_metadata(repo_path: Path, rows: list[dict[str, Any]]) -> None:
    """Write a small dataset card summarising the uploaded layers."""
    card = """# Air Traffic Warehouse (data lake)

Automatically generated by `scripts/upload_hf.py`.

## Contents

| Layer | Files |
|-------|-------|
"""

    counts: dict[str, int] = {}
    for _, uploaded_path in rows:
        layer = uploaded_path.split("/", 1)[0] if "/" in uploaded_path else "root"
        counts[layer] = counts.get(layer, 0) + 1

    for layer, count in sorted(counts.items()):
        card += f"| {layer} | {count} Parquet file(s) |\n"

    card += """
_Updated automatically on each ETL run._
"""
    (repo_path / "README.md").write_text(card, encoding="utf-8")


def upload_warehouse() -> dict[str, Any]:
    """Push bronze/silver/gold artifacts to the configured HF repo."""
    if not settings.huggingface_token:
        logger.warning("[hf] HF_TOKEN not set — skipping upload")
        return {"skipped": True, "reason": "HF_TOKEN not set"}

    try:
        from huggingface_hub import HfApi
    except ImportError as exc:  # pragma: no cover - optional dependency
        logger.warning("[hf] huggingface_hub not installed — skipping upload")
        return {"skipped": True, "reason": str(exc)}

    api = HfApi(token=settings.huggingface_token)
    repo = settings.huggingface_repo
    api.create_repo(repo_id=repo, repo_type="dataset", exist_ok=True)

    from huggingface_hub import CommitOperationAdd

    uploads = _plan_uploads()
    logger.info("[hf] uploading %s artifacts to %s", len(uploads), repo)

    operations = [
        CommitOperationAdd(path_in_repo=repo_path, path_or_fileobj=str(local_path))
        for local_path, repo_path in uploads
    ]

    api.create_commit(
        repo_id=repo,
        repo_type="dataset",
        commit_message="chore: ETL data refresh",
        operations=operations,
    )
    uploaded = len(operations)

    logger.info("[hf] uploaded %s artifacts to %s", uploaded, repo)
    return {"uploaded": uploaded, "repo": repo}


def main() -> None:
    result = upload_warehouse()
    print(json.dumps(result, indent=2))


if __name__ == "__main__":
    main()
